CREATE DATABASE SEPT_8;
USE SEPT_8;

CREATE TABLE HR
(ID INT PRIMARY KEY AUTO_INCREMENT,
First_Name varchar(30),
Last_Name varchar(30),
Depatment Enum ("Finance","HR","Operation")
);
INSERT INTO HR VALUES
(101,"HETI","PATEL","Finance");

INSERT INTO HR VALUES
(102,"HEER","PATEL","Operation");

INSERT INTO HR VALUES
(103,"NISHI","SHAH","HR");

INSERT INTO HR VALUES
(104,"HONEY","MEHTA","Finance");

CREATE TABLE EMPLOYEES
(CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
JOIN_DATE DATE,
DESIGNATION VARCHAR(20),
HR_NAME VARCHAR(20)
);
INSERT INTO EMPLOYEES VALUES
(101,"HONEY","MEHTA","2026-2-1","INTERN","SAM");



